version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        expose:
            - "9000"
        links:
            - db
        volumes:
            - ./www:/var/www
    db:
        build: ./images/mysql
        ports:
            - "3306:3306"
        volumes:
            - /etc/mysql:/etc/mysql
            - ./logs/mysql:/var/log/mysql
            - ./mysql:/var/lib/mysql
            - ./mysql-files:/var/lib/mysql-files
            - ./data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: finance-app
